// Generated by protoc-gen-zig — DO NOT EDIT
// Source: example.proto

const std = @import("std");
const _protobuf = @import("protobuf");
const _codegen = _protobuf._codegen;

pub const Foo = struct {
    name: []const u8 = "",
    id: i32 = 0,
    @"struct": u32 = 0,
    content: ?union(enum) {
        x: i32,
        y: []const u8,
    } = null,
    _unknown_fields: std.AutoHashMapUnmanaged(u32, std.ArrayListUnmanaged(_protobuf.UnknownField)) = .empty,

    pub fn getName(self: @This()) []const u8 {
        return self.name;
    }

    pub fn getId(self: @This()) i32 {
        return self.id;
    }

    pub fn getStruct(self: @This()) u32 {
        return self.@"struct";
    }

    pub fn getX(self: @This()) i32 {
        return if (self.content) |c| switch (c) {
            .x => |v| v,
            else => 0,
        } else 0;
    }

    pub fn getY(self: @This()) []const u8 {
        return if (self.content) |c| switch (c) {
            .y => |v| v,
            else => "",
        } else "";
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        _codegen.deinit_message(self, allocator);
    }

    pub const _metadata = _codegen.read_message_metadata(DESCRIPTOR_BYTES, .{0});

    pub fn _desc(io: std.Io) !*const _protobuf.DescMessage {
        return _codegen.messageDescAt(try _fileDesc(io), &[_]usize{0});
    }
};

pub const Bar = struct {
    foo: ?*Foo = null,
    tags: std.ArrayList([]const u8) = .empty,
    color: Color = @enumFromInt(0),
    colors: std.ArrayList(Color) = .empty,
    _unknown_fields: std.AutoHashMapUnmanaged(u32, std.ArrayListUnmanaged(_protobuf.UnknownField)) = .empty,

    pub const Nested = struct {
        value: i32 = 0,
        _unknown_fields: std.AutoHashMapUnmanaged(u32, std.ArrayListUnmanaged(_protobuf.UnknownField)) = .empty,

        pub fn getValue(self: @This()) i32 {
            return self.value;
        }

        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            _codegen.deinit_message(self, allocator);
        }

        pub const _metadata = _codegen.read_message_metadata(DESCRIPTOR_BYTES, .{ 1, 0 });

        pub fn _desc(io: std.Io) !*const _protobuf.DescMessage {
            return _codegen.messageDescAt(try _fileDesc(io), &[_]usize{ 1, 0 });
        }
    };

    pub fn getColor(self: @This()) Color {
        return self.color;
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        _codegen.deinit_message(self, allocator);
    }

    pub const _metadata = _codegen.read_message_metadata(DESCRIPTOR_BYTES, .{1});

    pub fn _desc(io: std.Io) !*const _protobuf.DescMessage {
        return _codegen.messageDescAt(try _fileDesc(io), &[_]usize{1});
    }
};

pub const Color = enum(i32) {
    COLOR_UNSPECIFIED = 0,
    COLOR_RED = 1,
    COLOR_GREEN = 2,
    COLOR_NEG = -1,
    _,
};

pub const DESCRIPTOR_BYTES: []const u8 = "\x0a\x0d\x65\x78\x61\x6d\x70\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x12\x07\x65\x78\x61\x6d\x70\x6c\x65\x22\x6c\x0a\x03\x46\x6f\x6f\x12\x12\x0a\x04\x6e\x61\x6d\x65\x18\x01\x20\x01\x28\x09\x52\x04\x6e\x61\x6d\x65\x12\x0e\x0a\x02\x69\x64\x18\x02\x20\x01\x28\x05\x52\x02\x69\x64\x12\x16\x0a\x06\x73\x74\x72\x75\x63\x74\x18\x03\x20\x01\x28\x0d\x52\x06\x73\x74\x72\x75\x63\x74\x12\x0e\x0a\x01\x78\x18\x04\x20\x01\x28\x05\x48\x00\x52\x01\x78\x12\x0e\x0a\x01\x79\x18\x05\x20\x01\x28\x09\x48\x00\x52\x01\x79\x42\x09\x0a\x07\x63\x6f\x6e\x74\x65\x6e\x74\x22\xa7\x01\x0a\x03\x42\x61\x72\x12\x1e\x0a\x03\x66\x6f\x6f\x18\x01\x20\x01\x28\x0b\x32\x0c\x2e\x65\x78\x61\x6d\x70\x6c\x65\x2e\x46\x6f\x6f\x52\x03\x66\x6f\x6f\x12\x12\x0a\x04\x74\x61\x67\x73\x18\x02\x20\x03\x28\x09\x52\x04\x74\x61\x67\x73\x12\x24\x0a\x05\x63\x6f\x6c\x6f\x72\x18\x03\x20\x01\x28\x0e\x32\x0e\x2e\x65\x78\x61\x6d\x70\x6c\x65\x2e\x43\x6f\x6c\x6f\x72\x52\x05\x63\x6f\x6c\x6f\x72\x12\x26\x0a\x06\x63\x6f\x6c\x6f\x72\x73\x18\x04\x20\x03\x28\x0e\x32\x0e\x2e\x65\x78\x61\x6d\x70\x6c\x65\x2e\x43\x6f\x6c\x6f\x72\x52\x06\x63\x6f\x6c\x6f\x72\x73\x1a\x1e\x0a\x06\x4e\x65\x73\x74\x65\x64\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x05\x52\x05\x76\x61\x6c\x75\x65\x2a\x56\x0a\x05\x43\x6f\x6c\x6f\x72\x12\x15\x0a\x11\x43\x4f\x4c\x4f\x52\x5f\x55\x4e\x53\x50\x45\x43\x49\x46\x49\x45\x44\x10\x00\x12\x0d\x0a\x09\x43\x4f\x4c\x4f\x52\x5f\x52\x45\x44\x10\x01\x12\x0f\x0a\x0b\x43\x4f\x4c\x4f\x52\x5f\x47\x52\x45\x45\x4e\x10\x02\x12\x16\x0a\x09\x43\x4f\x4c\x4f\x52\x5f\x4e\x45\x47\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06\x70\x72\x6f\x74\x6f\x33";

pub fn _fileDesc(io: std.Io) !*const _protobuf.DescFile {
    return _codegen.fileDesc(@This(), DESCRIPTOR_BYTES, &[_]_codegen.FileDescFn{}, io);
}
