// Generated by protoc-gen-zig — DO NOT EDIT
// Source: example.proto

pub const Foo = struct {
    name: ?[]const u8 = null,
    id: ?i32 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getId(self: @This()) i32 {
        return self.id orelse 0;
    }
};

pub const Bar = struct {
    // foo
    // tags
    pub const Nested = struct {
        value: ?i32 = null,

        pub fn getValue(self: @This()) i32 {
            return self.value orelse 0;
        }
    };
};
