// Generated by protoc-gen-zig — DO NOT EDIT
// Source: import/import_main.proto

const std = @import("std");
const _codegen = @import("protobuf")._codegen;
const _metadata = _codegen.metadata;
const _import_import_dep = @import("import_dep.pb.zig");

pub const ImportMain = struct {
    single: ?*_import_import_dep.DepMsg = null,
    kind: ?_import_import_dep.DepEnum = null,
    many: std.ArrayList(*_import_import_dep.DepMsg) = .empty,
    kinds: std.ArrayList(_import_import_dep.DepEnum) = .empty,

    pub fn getKind(self: @This()) _import_import_dep.DepEnum {
        return self.kind orelse @enumFromInt(0);
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        _codegen.deinit_message(self, allocator);
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .message_field = .{} } }, // single
            .{ .number = 2, .field_index = 1, .kind = .{ .enum_field = .{ .default_value = 0 } } }, // kind
            .{ .number = 3, .field_index = 2, .kind = .{ .list = .{ .element = .{ .message = {} } } } }, // many
            .{ .number = 4, .field_index = 3, .kind = .{ .list = .{ .element = .{ .enum_type = {} }, .is_packed = true } } }, // kinds
        },
    };
};

pub const DESCRIPTOR_BYTES: []const u8 = "\x0a\x18\x69\x6d\x70\x6f\x72\x74\x2f\x69\x6d\x70\x6f\x72\x74\x5f\x6d\x61\x69\x6e\x2e\x70\x72\x6f\x74\x6f\x12\x04\x6d\x61\x69\x6e\x1a\x17\x69\x6d\x70\x6f\x72\x74\x2f\x69\x6d\x70\x6f\x72\x74\x5f\x64\x65\x70\x2e\x70\x72\x6f\x74\x6f\x22\x98\x01\x0a\x0a\x49\x6d\x70\x6f\x72\x74\x4d\x61\x69\x6e\x12\x23\x0a\x06\x73\x69\x6e\x67\x6c\x65\x18\x01\x20\x01\x28\x0b\x32\x0b\x2e\x64\x65\x70\x2e\x44\x65\x70\x4d\x73\x67\x52\x06\x73\x69\x6e\x67\x6c\x65\x12\x20\x0a\x04\x6b\x69\x6e\x64\x18\x02\x20\x01\x28\x0e\x32\x0c\x2e\x64\x65\x70\x2e\x44\x65\x70\x45\x6e\x75\x6d\x52\x04\x6b\x69\x6e\x64\x12\x1f\x0a\x04\x6d\x61\x6e\x79\x18\x03\x20\x03\x28\x0b\x32\x0b\x2e\x64\x65\x70\x2e\x44\x65\x70\x4d\x73\x67\x52\x04\x6d\x61\x6e\x79\x12\x22\x0a\x05\x6b\x69\x6e\x64\x73\x18\x04\x20\x03\x28\x0e\x32\x0c\x2e\x64\x65\x70\x2e\x44\x65\x70\x45\x6e\x75\x6d\x52\x05\x6b\x69\x6e\x64\x73\x62\x06\x70\x72\x6f\x74\x6f\x33";
