// Generated by protoc-gen-zig — DO NOT EDIT
// Source: import/import_dep.proto

const std = @import("std");
const _codegen = @import("protobuf")._codegen;
const _metadata = _codegen.metadata;

pub const DepMsg = struct {
    label: ?[]const u8 = null,

    pub fn getLabel(self: @This()) []const u8 {
        return self.label orelse "";
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        _codegen.deinit_message(self, allocator);
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // label
        },
    };
};

pub const DepEnum = enum(i32) {
    DEP_UNSPECIFIED = 0,
    DEP_A = 1,
    DEP_B = 2,
    _,
};

pub const DESCRIPTOR_BYTES: []const u8 = "\x0a\x17\x69\x6d\x70\x6f\x72\x74\x2f\x69\x6d\x70\x6f\x72\x74\x5f\x64\x65\x70\x2e\x70\x72\x6f\x74\x6f\x12\x03\x64\x65\x70\x22\x1e\x0a\x06\x44\x65\x70\x4d\x73\x67\x12\x14\x0a\x05\x6c\x61\x62\x65\x6c\x18\x01\x20\x01\x28\x09\x52\x05\x6c\x61\x62\x65\x6c\x2a\x34\x0a\x07\x44\x65\x70\x45\x6e\x75\x6d\x12\x13\x0a\x0f\x44\x45\x50\x5f\x55\x4e\x53\x50\x45\x43\x49\x46\x49\x45\x44\x10\x00\x12\x09\x0a\x05\x44\x45\x50\x5f\x41\x10\x01\x12\x09\x0a\x05\x44\x45\x50\x5f\x42\x10\x02\x62\x06\x70\x72\x6f\x74\x6f\x33";
