const std = @import("std");
const descriptor = @import("gen_old/google/protobuf.pb.zig");
const protobuf = @import("our_protobuf");
const GeneratedFile = @import("generated_file.zig").GeneratedFile;

const ImportTable = std.AutoArrayHashMap(*const protobuf.DescFile, []const u8);

pub fn generateFile(
    alloc: std.mem.Allocator,
    desc_file: *const protobuf.DescFile,
    file_proto: *const descriptor.FileDescriptorProto,
) ![]u8 {
    var f = GeneratedFile.init(alloc);

    // Build import table from direct proto imports for this file.
    var imports = ImportTable.init(alloc);
    defer {
        for (imports.values()) |alias| alloc.free(alias);
        imports.deinit();
    }
    for (desc_file.dependencies) |dep_file| {
        const alias = try aliasFor(alloc, dep_file);
        try imports.put(dep_file, alias);
    }

    try f.writeLine("// Generated by protoc-gen-zig — DO NOT EDIT");
    try f.writeLine(.{ "// Source: ", desc_file.name });
    try f.emptyLine();

    // TODO make sure this is always correct
    if (desc_file.messages.len > 0) {
        try f.writeLine("const std = @import(\"std\");");
        try f.writeLine("const _codegen = @import(\"protobuf\")._codegen;");
        try f.writeLine("const _metadata = _codegen.metadata;");
        const current_is_wkt = wktModuleName(desc_file.name) != null;
        for (imports.keys(), imports.values()) |dep_file, alias| {
            if (!current_is_wkt) {
                if (wktModuleName(dep_file.name)) |module| {
                    try f.writeLine(.{ "const ", alias, " = @import(\"protobuf\").wkt.", module, ";" });
                    continue;
                }
            }
            const rel_path = try relativeImportPath(alloc, desc_file.name, dep_file.name);
            defer alloc.free(rel_path);
            try f.writeLine(.{ "const ", alias, " = @import(\"", rel_path, "\");" });
        }
        try f.emptyLine();
    }

    for (desc_file.messages) |*msg| {
        try generateMessage(&f, msg, desc_file, &imports);
    }

    for (desc_file.enums) |*e| {
        try generateEnum(&f, e);
    }

    try f.emptyLine();
    try emitDescriptorBytes(&f, file_proto, alloc);

    const raw = try f.toOwnedSlice();
    defer alloc.free(raw);
    return try formatZigSource(alloc, raw);
}

fn formatZigSource(alloc: std.mem.Allocator, source: []const u8) ![]u8 {
    const source_z = try alloc.dupeZ(u8, source);
    defer alloc.free(source_z);
    var tree = try std.zig.Ast.parse(alloc, source_z, .zig);
    defer tree.deinit(alloc);
    if (tree.errors.len != 0) return error.GeneratedSourceHasParseErrors;
    return tree.renderAlloc(alloc);
}

fn generateMessage(
    f: *GeneratedFile,
    msg: *const protobuf.DescMessage,
    cur_file: *const protobuf.DescFile,
    imports: *const ImportTable,
) !void {
    // TODO escape directly local_name
    const safe_name = try escapeZigKeyword(f.alloc, msg.local_name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = struct {" });
    f.indent();

    // Plain scalar/message/list/enum struct fields (not in a oneof).
    for (msg.fields) |*field| {
        if (!isPlainScalar(field) and !isPlainMessage(field) and !isPlainList(field) and !isPlainEnum(field)) continue;
        try generateField(f, field, cur_file, imports);
    }
    // Oneof union fields (synthetic proto3-optional oneofs are excluded from msg.oneofs).
    for (msg.oneofs) |*oneof| {
        try generateOneofField(f, oneof);
    }
    try f.emptyLine();

    for (msg.nested_messages) |*nested| {
        try generateMessage(f, nested, cur_file, imports);
    }

    for (msg.nested_enums) |*e| {
        try generateEnum(f, e);
    }

    // Plain scalar field getters (message fields have no getter).
    for (msg.fields) |*field| {
        if (isPlainScalar(field)) {
            try generateFieldGetter(f, field);
        }
        if (isPlainEnum(field)) {
            try generateEnumFieldGetter(f, field, cur_file, imports);
        }
    }
    // Oneof variant getters.
    for (msg.oneofs) |*oneof| {
        try generateOneofVariantGetters(f, oneof);
    }

    try f.emptyLine();
    try generateMessageDeinit(f);

    try f.emptyLine();
    try generateMessageMetadata(f, msg);

    f.unindent();
    try f.writeLine("};");

    try f.emptyLine();
}

fn generateEnum(
    f: *GeneratedFile,
    e: *const protobuf.DescEnum,
) !void {
    // TODO escape directly local_name
    const safe_name = try escapeZigKeyword(f.alloc, e.local_name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = enum(i32) {" });
    f.indent();

    for (e.values, 0..) |*v, i| {
        // Skip alias values (allow_alias enums declare multiple names for the same number).
        // Zig rejects duplicate enum tag values; emit only the first occurrence of each number.
        if (e.value.get(v.number)) |first_idx| {
            if (first_idx != i) continue;
        }
        const safe_value_name = try escapeZigKeyword(f.alloc, v.local_name);
        defer f.alloc.free(safe_value_name);
        try f.writeLine(.{ safe_value_name, " = ", v.number, "," });
    }

    try f.writeLine("_,");

    f.unindent();
    try f.writeLine("};");
    try f.emptyLine();
}

fn generateMessageDeinit(f: *GeneratedFile) !void {
    try f.writeLine("pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {");
    f.indent();
    try f.writeLine("_codegen.deinit_message(self, allocator);");
    f.unindent();
    try f.writeLine("}");
}

fn generateMessageMetadata(
    f: *GeneratedFile,
    msg: *const protobuf.DescMessage,
) !void {
    try f.writeLine("pub const _desc = _metadata.MessageMetadata{");
    f.indent();
    try f.writeLine(".fields = &[_]_metadata.FieldMetadata{");
    f.indent();

    var field_index: u32 = 0;

    // Plain scalar/message/list fields (not in a oneof) — must mirror the struct field loop.
    for (msg.fields) |*field| {
        if (isPlainScalar(field)) {
            try f.writeLine(.{
                ".{ .number = ",
                field.number,
                ", .field_index = ",
                field_index,
                ", .kind = .{ .scalar = .{ .scalar = .",
                @tagName(field.kind.scalar.scalar),
                " } } }, // ",
                field.name,
            });
            field_index += 1;
        } else if (isPlainMessage(field)) {
            try f.writeLine(.{
                ".{ .number = ",
                field.number,
                ", .field_index = ",
                field_index,
                ", .kind = .{ .message_field = .{} } }, // ",
                field.name,
            });
            field_index += 1;
        } else if (isPlainEnum(field)) {
            const default = field.kind.enum_field.default_value orelse 0;
            try f.writeLine(.{
                ".{ .number = ",
                field.number,
                ", .field_index = ",
                field_index,
                ", .kind = .{ .enum_field = .{ .default_value = ",
                default,
                " } } }, // ",
                field.name,
            });
            field_index += 1;
        } else if (isPlainList(field)) {
            const list = field.kind.list;
            const packed_suffix: []const u8 = if (list.is_packed) ", .is_packed = true" else "";
            switch (list.element) {
                .scalar => |sc| {
                    try f.writeLine(.{
                        ".{ .number = ",
                        field.number,
                        ", .field_index = ",
                        field_index,
                        ", .presence = .implicit, .kind = .{ .list = .{ .element = .{ .scalar = .",
                        @tagName(sc),
                        " }",
                        packed_suffix,
                        " } } }, // ",
                        field.name,
                    });
                },
                .message => {
                    try f.writeLine(.{
                        ".{ .number = ",
                        field.number,
                        ", .field_index = ",
                        field_index,
                        ", .presence = .implicit, .kind = .{ .list = .{ .element = .{ .message = {} } } } }, // ",
                        field.name,
                    });
                },
                .enum_type => {
                    try f.writeLine(.{
                        ".{ .number = ",
                        field.number,
                        ", .field_index = ",
                        field_index,
                        ", .presence = .implicit, .kind = .{ .list = .{ .element = .{ .enum_type = {} }",
                        packed_suffix,
                        " } } }, // ",
                        field.name,
                    });
                },
            }
            field_index += 1;
        }
    }

    // Oneof variant entries — all variants of a group share the same field_index.
    for (msg.oneofs) |*oneof| {
        for (oneof.fields) |field_ptr| {
            if (field_ptr.kind != .scalar) continue;
            try f.writeLine(.{
                ".{ .number = ",
                field_ptr.number,
                ", .field_index = ",
                field_index,
                ", .oneof_variant = \"",
                field_ptr.name,
                "\", .kind = .{ .scalar = .{ .scalar = .",
                @tagName(field_ptr.kind.scalar.scalar),
                " } } }, // ",
                field_ptr.name,
            });
        }
        field_index += 1;
    }

    f.unindent();
    try f.writeLine("},");
    f.unindent();
    try f.writeLine("};");
}

fn generateField(
    f: *GeneratedFile,
    field: *const protobuf.DescField,
    cur_file: *const protobuf.DescFile,
    imports: *const ImportTable,
) !void {
    // field.local_name is already keyword-escaped by the descriptor builder.
    switch (field.kind) {
        .scalar => |sc| {
            try f.writeLine(.{ field.local_name, ": ?", scalarZigType(sc.scalar), " = null," });
        },
        .message_field => |mf| {
            const type_name = try messageZigTypeName(f.alloc, mf.message, cur_file, imports);
            defer f.alloc.free(type_name);
            try f.writeLine(.{ field.local_name, ": ?*", type_name, " = null," });
        },
        .enum_field => |ef| {
            const type_name = try enumZigTypeName(f.alloc, ef.enum_type, cur_file, imports);
            defer f.alloc.free(type_name);
            try f.writeLine(.{ field.local_name, ": ?", type_name, " = null," });
        },
        .list => |list| {
            switch (list.element) {
                .scalar => |sc| {
                    try f.writeLine(.{ field.local_name, ": std.ArrayListUnmanaged(", scalarZigType(sc), ") = .{}," });
                },
                .message => |m| {
                    const type_name = try messageZigTypeName(f.alloc, m, cur_file, imports);
                    defer f.alloc.free(type_name);
                    try f.writeLine(.{ field.local_name, ": std.ArrayListUnmanaged(*", type_name, ") = .{}," });
                },
                .enum_type => |e| {
                    const type_name = try enumZigTypeName(f.alloc, e, cur_file, imports);
                    defer f.alloc.free(type_name);
                    try f.writeLine(.{ field.local_name, ": std.ArrayListUnmanaged(", type_name, ") = .{}," });
                },
            }
        },
        else => unreachable,
    }
}

fn generateOneofField(
    f: *GeneratedFile,
    oneof: *const protobuf.DescOneof,
) !void {
    const safe_name = try escapeZigKeyword(f.alloc, oneof.local_name);
    defer f.alloc.free(safe_name);
    try f.write(.{ safe_name, ": ?union(enum) {" });
    for (oneof.fields) |field_ptr| {
        if (field_ptr.kind != .scalar) continue;
        // field_ptr.local_name is already keyword-escaped.
        try f.write(.{ " ", field_ptr.local_name, ": ", scalarZigType(field_ptr.kind.scalar.scalar), "," });
    }
    try f.writeLine(" } = null,");
}

fn generateOneofVariantGetters(
    f: *GeneratedFile,
    oneof: *const protobuf.DescOneof,
) !void {
    const safe_oneof_name = try escapeZigKeyword(f.alloc, oneof.local_name);
    defer f.alloc.free(safe_oneof_name);
    for (oneof.fields) |field_ptr| {
        if (field_ptr.kind != .scalar) continue;
        const getter_name = try toCamelCase(f.alloc, field_ptr.name);
        defer f.alloc.free(getter_name);
        const default = scalarDefaultLiteral(field_ptr.kind.scalar.scalar);
        try f.emptyLine();
        try f.writeLine(.{ "pub fn get", getter_name, "(self: @This()) ", scalarZigType(field_ptr.kind.scalar.scalar), " {" });
        f.indent();
        try f.writeLine(.{
            "return if (self.",   safe_oneof_name,       ") |c| switch (c) { .",
            field_ptr.local_name, " => |v| v, else => ", default,
            " } else ",           default,               ";",
        });
        f.unindent();
        try f.writeLine("}");
    }
}

fn generateFieldGetter(
    f: *GeneratedFile,
    field: *const protobuf.DescField,
) !void {
    // TODO make sure the new name doesn't conflict with any existing member
    const field_name_camel = try toCamelCase(f.alloc, field.name);
    defer f.alloc.free(field_name_camel);

    // field.local_name is already keyword-escaped.
    const zig_type = scalarZigType(field.kind.scalar.scalar);
    const default = scalarDefaultLiteral(field.kind.scalar.scalar);

    try f.emptyLine();
    try f.writeLine(.{ "pub fn get", field_name_camel, "(self: @This()) ", zig_type, " {" });
    f.indent();
    try f.writeLine(.{ "return self.", field.local_name, " orelse ", default, ";" });
    f.unindent();
    try f.writeLine("}");
}

/// Returns true for a non-oneof scalar field (emitted as a plain struct field).
fn isPlainScalar(field: *const protobuf.DescField) bool {
    return field.kind == .scalar and field.kind.scalar.oneof == null;
}

/// Returns true for a non-oneof singular message field.
fn isPlainMessage(field: *const protobuf.DescField) bool {
    if (field.kind != .message_field) return false;
    if (field.kind.message_field.oneof != null) return false;
    return true;
}

/// Returns true for a repeated scalar, message, or enum field.
/// Map fields are skipped (not yet supported).
fn isPlainList(field: *const protobuf.DescField) bool {
    if (field.kind != .list) return false;
    return switch (field.kind.list.element) {
        .scalar, .message, .enum_type => true,
    };
}

/// Returns true for a non-oneof singular enum field.
fn isPlainEnum(field: *const protobuf.DescField) bool {
    if (field.kind != .enum_field) return false;
    if (field.kind.enum_field.oneof != null) return false;
    return true;
}

/// Builds the Zig type path for a message type.
///
/// For same-file types produces a file-root-relative dotted path (e.g. "Outer.Inner").
/// For cross-file types prepends the import alias (e.g. "_dep.Outer.Inner").
fn messageZigTypeName(
    alloc: std.mem.Allocator,
    msg: *const protobuf.DescMessage,
    cur_file: *const protobuf.DescFile,
    imports: *const ImportTable,
) ![]u8 {
    // Collect path components from the message up to the top-level.
    var parts: std.ArrayList([]u8) = .{};
    defer {
        for (parts.items) |p| alloc.free(p);
        parts.deinit(alloc);
    }

    var cur: ?*const protobuf.DescMessage = msg;
    while (cur) |m| {
        const escaped = try escapeZigKeyword(alloc, m.local_name);
        try parts.append(alloc, escaped);
        cur = m.parent;
    }

    // Reverse so we get outermost first.
    std.mem.reverse([]u8, parts.items);

    const local_path = try std.mem.join(alloc, ".", parts.items);
    if (msg.file != cur_file) {
        defer alloc.free(local_path);
        const alias = imports.get(msg.file) orelse unreachable;
        return std.fmt.allocPrint(alloc, "{s}.{s}", .{ alias, local_path });
    }
    return local_path;
}

/// Builds the Zig type path for an enum type.
///
/// For same-file types mirrors messageZigTypeName (e.g. "Outer.MyEnum").
/// For cross-file top-level enums prepends the import alias (e.g. "_dep.MyEnum").
/// For cross-file nested enums the parent chain carries the alias (e.g. "_dep.Outer.MyEnum").
fn enumZigTypeName(
    alloc: std.mem.Allocator,
    e: *const protobuf.DescEnum,
    cur_file: *const protobuf.DescFile,
    imports: *const ImportTable,
) ![]u8 {
    const safe_name = try escapeZigKeyword(alloc, e.local_name);
    if (e.parent) |parent_msg| {
        defer alloc.free(safe_name);
        const parent_path = try messageZigTypeName(alloc, parent_msg, cur_file, imports);
        defer alloc.free(parent_path);
        return std.fmt.allocPrint(alloc, "{s}.{s}", .{ parent_path, safe_name });
    } else if (e.file != cur_file) {
        defer alloc.free(safe_name);
        const alias = imports.get(e.file) orelse unreachable;
        return std.fmt.allocPrint(alloc, "{s}.{s}", .{ alias, safe_name });
    }
    return safe_name;
}

fn generateEnumFieldGetter(
    f: *GeneratedFile,
    field: *const protobuf.DescField,
    cur_file: *const protobuf.DescFile,
    imports: *const ImportTable,
) !void {
    const field_name_camel = try toCamelCase(f.alloc, field.name);
    defer f.alloc.free(field_name_camel);

    const zig_type = try enumZigTypeName(f.alloc, field.kind.enum_field.enum_type, cur_file, imports);
    defer f.alloc.free(zig_type);

    const default = field.kind.enum_field.default_value orelse 0;

    try f.emptyLine();
    try f.writeLine(.{ "pub fn get", field_name_camel, "(self: @This()) ", zig_type, " {" });
    f.indent();
    try f.writeLine(.{ "return self.", field.local_name, " orelse @enumFromInt(", default, ");" });
    f.unindent();
    try f.writeLine("}");
}

fn scalarZigType(t: protobuf.ScalarType) []const u8 {
    return switch (t) {
        .double => "f64",
        .float => "f32",
        .int64, .sint64, .sfixed64 => "i64",
        .uint64, .fixed64 => "u64",
        .int32, .sint32, .sfixed32 => "i32",
        .uint32, .fixed32 => "u32",
        .bool => "bool",
        .string, .bytes => "[]const u8",
    };
}

fn scalarDefaultLiteral(t: protobuf.ScalarType) []const u8 {
    return switch (t) {
        .double, .float => "0.0",
        .int64, .sint64, .sfixed64, .uint64, .fixed64, .int32, .sint32, .sfixed32, .uint32, .fixed32 => "0",
        .bool => "false",
        .string, .bytes => "\"\"",
    };
}

pub fn escapeZigKeyword(alloc: std.mem.Allocator, name: []const u8) ![]u8 {
    if (std.zig.Token.keywords.has(name)) {
        return std.fmt.allocPrint(alloc, "@\"{s}\"", .{name});
    }
    return alloc.dupe(u8, name);
}

fn emitDescriptorBytes(
    f: *GeneratedFile,
    file: *const descriptor.FileDescriptorProto,
    alloc: std.mem.Allocator,
) !void {
    var w: std.Io.Writer.Allocating = .init(alloc);
    defer w.deinit();

    // Strip source_code_info before encoding
    var stripped = file.*;
    stripped.source_code_info = null;
    try stripped.encode(&w.writer, alloc);
    const bytes = w.written();

    // TODO: make sure variable name doesn't conflict with any existing identifier
    try f.write("pub const DESCRIPTOR_BYTES: []const u8 = \"");
    var buf: [4]u8 = undefined;
    for (bytes) |b| {
        const s = try std.fmt.bufPrint(&buf, "\\x{x:0>2}", .{b});
        try f.write(s);
    }
    try f.writeLine("\";");
}

pub fn toCamelCase(alloc: std.mem.Allocator, snake: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .{};
    try out.ensureTotalCapacity(alloc, snake.len);
    var upper_next = true;
    for (snake) |c| {
        if (c == '_') {
            upper_next = true;
            continue;
        }
        try out.append(alloc, if (upper_next) std.ascii.toUpper(c) else c);
        upper_next = false;
    }
    return out.toOwnedSlice(alloc);
}

/// Computes the alias for an imported file's generated binding.
///
/// Strips the ".proto" suffix, replaces non-alphanumeric characters with "_",
/// and prepends "_".
fn aliasFor(alloc: std.mem.Allocator, dep_file: *const protobuf.DescFile) ![]u8 {
    const name = dep_file.name;
    const base = name[0 .. name.len - ".proto".len];
    const buf = try alloc.alloc(u8, base.len + 1);
    buf[0] = '_';
    for (base, 0..) |c, i| {
        buf[i + 1] = if (std.ascii.isAlphanumeric(c)) c else '_';
    }
    return buf;
}

fn wktModuleName(proto_name: []const u8) ?[]const u8 {
    const entries = .{
        .{ "google/protobuf/any.proto", "any" },
        .{ "google/protobuf/api.proto", "api" },
        .{ "google/protobuf/cpp_features.proto", "cpp_features" },
        .{ "google/protobuf/descriptor.proto", "descriptor" },
        .{ "google/protobuf/duration.proto", "duration" },
        .{ "google/protobuf/empty.proto", "empty" },
        .{ "google/protobuf/field_mask.proto", "field_mask" },
        .{ "google/protobuf/go_features.proto", "go_features" },
        .{ "google/protobuf/java_features.proto", "java_features" },
        .{ "google/protobuf/source_context.proto", "source_context" },
        .{ "google/protobuf/struct.proto", "struct_" },
        .{ "google/protobuf/timestamp.proto", "timestamp" },
        .{ "google/protobuf/type.proto", "type_" },
        .{ "google/protobuf/wrappers.proto", "wrappers" },
    };
    inline for (entries) |entry| {
        if (std.mem.eql(u8, proto_name, entry[0])) return entry[1];
    }
    return null;
}

/// Computes the relative @import path from the importer file to the dep file,
/// both expressed as proto source paths (e.g. "google/protobuf/compiler/plugin.proto").
///
/// The result uses forward slashes and is suitable for direct use in @import("...").
fn relativeImportPath(alloc: std.mem.Allocator, from_proto: []const u8, to_proto: []const u8) ![]u8 {
    const from_base = from_proto[0 .. from_proto.len - ".proto".len];
    const to_base = to_proto[0 .. to_proto.len - ".proto".len];

    // dirname: everything before last '/', or empty string
    const from_dir: []const u8 = if (std.mem.lastIndexOf(u8, from_base, "/")) |i| from_base[0..i] else "";
    const to_dir: []const u8 = if (std.mem.lastIndexOf(u8, to_base, "/")) |i| to_base[0..i] else "";
    // basename of the dep file (without extension)
    const to_file_base: []const u8 = if (std.mem.lastIndexOf(u8, to_base, "/")) |i| to_base[i + 1 ..] else to_base;

    // Split directory paths into segments
    var from_segs: std.ArrayList([]const u8) = .{};
    defer from_segs.deinit(alloc);
    var to_segs: std.ArrayList([]const u8) = .{};
    defer to_segs.deinit(alloc);

    if (from_dir.len > 0) {
        var it = std.mem.splitScalar(u8, from_dir, '/');
        while (it.next()) |seg| try from_segs.append(alloc, seg);
    }
    if (to_dir.len > 0) {
        var it = std.mem.splitScalar(u8, to_dir, '/');
        while (it.next()) |seg| try to_segs.append(alloc, seg);
    }

    // Find the number of leading directory segments in common
    var common: usize = 0;
    while (common < from_segs.items.len and common < to_segs.items.len and
        std.mem.eql(u8, from_segs.items[common], to_segs.items[common]))
    {
        common += 1;
    }

    // Build the relative path parts: "../" for each non-common from-dir level,
    // then the remaining to-dir segments, then the dep file name.
    var parts: std.ArrayList([]const u8) = .{};
    defer parts.deinit(alloc);

    for (0..from_segs.items.len - common) |_| try parts.append(alloc, "..");
    for (to_segs.items[common..]) |seg| try parts.append(alloc, seg);
    const to_file = try std.mem.concat(alloc, u8, &.{ to_file_base, ".pb.zig" });
    defer alloc.free(to_file);
    try parts.append(alloc, to_file);

    return std.mem.join(alloc, "/", parts.items);
}
