const std = @import("std");
const descriptor = @import("gen/google/protobuf.pb.zig");
const GeneratedFile = @import("generated_file.zig").GeneratedFile;

const FieldType = descriptor.FieldDescriptorProto.Type;

pub fn generateFile(
    alloc: std.mem.Allocator,
    file: *const descriptor.FileDescriptorProto,
) ![]u8 {
    var f = GeneratedFile.init(alloc);

    try f.writeLine("// Generated by protoc-gen-zig — DO NOT EDIT");
    try f.writeLine(.{ "// Source: ", file.name orelse @panic("File without name") });
    try f.emptyLine();

    if (file.message_type.items.len > 0) {
        try f.writeLine("const _metadata = @import(\"protobuf\")._metadata;");
        try f.emptyLine();
    }

    for (file.message_type.items) |*msg| {
        try generateMessage(&f, msg);
    }

    for (file.enum_type.items) |*e| {
        try generateEnum(&f, e);
    }

    const raw = try f.toOwnedSlice();
    defer alloc.free(raw);
    return try formatZigSource(alloc, raw);
}

fn formatZigSource(alloc: std.mem.Allocator, source: []const u8) ![]u8 {
    const source_z = try alloc.dupeZ(u8, source);
    defer alloc.free(source_z);
    var tree = try std.zig.Ast.parse(alloc, source_z, .zig);
    defer tree.deinit(alloc);
    if (tree.errors.len != 0) return error.GeneratedSourceHasParseErrors;
    return tree.renderAlloc(alloc);
}

fn generateMessage(
    f: *GeneratedFile,
    msg: *const descriptor.DescriptorProto,
) !void {
    const name = msg.name orelse @panic("Message without name");
    const safe_name = try escapeZigKeyword(f.alloc, name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = struct {" });
    f.indent();

    for (msg.field.items) |*field| {
        try generateField(f, field);
    }
    for (msg.oneof_decl.items, 0..) |*oneof, i| {
        const oneof_name = oneof.name orelse @panic("Oneof without name");
        try generateOneofField(f, msg, oneof_name, @intCast(i));
    }
    try f.emptyLine();

    for (msg.nested_type.items) |*nested| {
        try generateMessage(f, nested);
    }

    for (msg.enum_type.items) |*e| {
        try generateEnum(f, e);
    }

    for (msg.field.items) |*field| {
        try generateFieldGetter(f, field);
    }
    for (msg.oneof_decl.items, 0..) |*oneof, i| {
        const oneof_name = oneof.name orelse @panic("Oneof without name");
        try generateOneofVariantGetters(f, msg, oneof_name, @intCast(i));
    }

    try f.emptyLine();
    try generateMessageMetadata(f, msg);

    f.unindent();
    try f.writeLine("};");

    try f.emptyLine();
}

fn generateEnum(
    f: *GeneratedFile,
    e: *const descriptor.EnumDescriptorProto,
) !void {
    const name = e.name orelse @panic("Enum without name");
    const safe_name = try escapeZigKeyword(f.alloc, name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = enum(i32) {" });
    f.indent();

    for (e.value.items) |*v| {
        const value_name = v.name orelse @panic("Enum value without name");
        const value_number = v.number orelse @panic("Enum value without number");
        const safe_value_name = try escapeZigKeyword(f.alloc, value_name);
        defer f.alloc.free(safe_value_name);
        try f.writeLine(.{ safe_value_name, " = ", value_number, "," });
    }

    try f.writeLine("_,");

    f.unindent();
    try f.writeLine("};");
    try f.emptyLine();
}

fn generateMessageMetadata(
    f: *GeneratedFile,
    msg: *const descriptor.DescriptorProto,
) !void {
    try f.writeLine("pub const _desc = _metadata.MessageMetadata{");
    f.indent();
    try f.writeLine(".fields = &[_]_metadata.FieldMetadata{");
    f.indent();

    var field_index: u32 = 0;

    // Regular scalar fields.
    for (msg.field.items) |*field| {
        if (!isPlainScalarField(field)) continue;
        const field_name = field.name orelse @panic("Field without name");
        const number = field.number orelse @panic("Field without number");
        const scalar_name = scalarMetadataName(field.type.?);
        try f.writeLine(.{
            ".{ .number = ",
            number,
            ", .field_index = ",
            field_index,
            ", .kind = .{ .scalar = .{ .scalar = .",
            scalar_name,
            " } } }, // ",
            field_name,
        });
        field_index += 1;
    }

    // Oneof variant entries — all variants of a group share the same field_index.
    for (msg.oneof_decl.items, 0..) |_, i| {
        const oneof_idx: i32 = @intCast(i);
        for (msg.field.items) |*field| {
            if (field.oneof_index != oneof_idx) continue;
            if (field.proto3_optional == true) continue;
            const t = field.type orelse @panic("Field without type");
            if (!isScalarFieldType(t)) continue;
            const variant_name = field.name orelse @panic("Field without name");
            const number = field.number orelse @panic("Field without number");
            try f.writeLine(.{
                ".{ .number = ",
                number,
                ", .field_index = ",
                field_index,
                ", .oneof_variant = \"",
                variant_name,
                "\", .kind = .{ .scalar = .{ .scalar = .",
                scalarMetadataName(t),
                " } } }, // ",
                variant_name,
            });
        }
        field_index += 1;
    }

    f.unindent();
    try f.writeLine("},");
    f.unindent();
    try f.writeLine("};");
}

fn generateField(
    f: *GeneratedFile,
    field: *const descriptor.FieldDescriptorProto,
) !void {
    if (!isPlainScalarField(field)) return;
    const field_name = field.name orelse return;
    const zig_type = scalarZigType(field.type.?);
    const safe_field_name = try escapeZigKeyword(f.alloc, field_name);
    defer f.alloc.free(safe_field_name);
    try f.writeLine(.{ safe_field_name, ": ?", zig_type, " = null," });
}

fn generateOneofField(
    f: *GeneratedFile,
    msg: *const descriptor.DescriptorProto,
    oneof_name: []const u8,
    oneof_idx: i32,
) !void {
    const safe_name = try escapeZigKeyword(f.alloc, oneof_name);
    defer f.alloc.free(safe_name);
    try f.write(.{ safe_name, ": ?union(enum) {" });
    for (msg.field.items) |*field| {
        if (field.oneof_index != oneof_idx) continue;
        if (field.proto3_optional == true) continue;
        const t = field.type orelse @panic("Field without type");
        if (!isScalarFieldType(t)) continue;
        const variant_name = field.name orelse @panic("Field without name");
        const safe_variant = try escapeZigKeyword(f.alloc, variant_name);
        defer f.alloc.free(safe_variant);
        try f.write(.{ " ", safe_variant, ": ", scalarZigType(t), "," });
    }
    try f.writeLine(" } = null,");
}

fn generateOneofVariantGetters(
    f: *GeneratedFile,
    msg: *const descriptor.DescriptorProto,
    oneof_name: []const u8,
    oneof_idx: i32,
) !void {
    const safe_oneof_name = try escapeZigKeyword(f.alloc, oneof_name);
    defer f.alloc.free(safe_oneof_name);
    for (msg.field.items) |*field| {
        if (field.oneof_index != oneof_idx) continue;
        if (field.proto3_optional == true) continue;
        const t = field.type orelse continue;
        if (!isScalarFieldType(t)) continue;
        const variant_name = field.name orelse @panic("Field without name");
        const safe_variant = try escapeZigKeyword(f.alloc, variant_name);
        defer f.alloc.free(safe_variant);
        const getter_name = try toCamelCase(f.alloc, variant_name);
        defer f.alloc.free(getter_name);
        const default = scalarDefaultLiteral(t);
        try f.emptyLine();
        try f.writeLine(.{ "pub fn get", getter_name, "(self: @This()) ", scalarZigType(t), " {" });
        f.indent();
        try f.writeLine(.{
            "return if (self.", safe_oneof_name,       ") |c| switch (c) { .",
            safe_variant,       " => |v| v, else => ", default,
            " } else ",         default,               ";",
        });
        f.unindent();
        try f.writeLine("}");
    }
}

fn generateFieldGetter(
    f: *GeneratedFile,
    field: *const descriptor.FieldDescriptorProto,
) !void {
    if (!isPlainScalarField(field)) return;
    const field_name = field.name orelse return;

    // TODO make sure the new name doesn't conflict with any existing member
    const field_name_camel = try toCamelCase(f.alloc, field_name);
    defer f.alloc.free(field_name_camel);

    const safe_field_name = try escapeZigKeyword(f.alloc, field_name);
    defer f.alloc.free(safe_field_name);

    const zig_type = scalarZigType(field.type.?);
    const default = scalarDefaultLiteral(field.type.?);

    try f.emptyLine();
    try f.writeLine(.{ "pub fn get", field_name_camel, "(self: @This()) ", zig_type, " {" });
    f.indent();
    try f.writeLine(.{ "return self.", safe_field_name, " orelse ", default, ";" });
    f.unindent();
    try f.writeLine("}");
}

fn isScalarFieldType(t: FieldType) bool {
    return switch (t) {
        .TYPE_DOUBLE, .TYPE_FLOAT, .TYPE_INT64, .TYPE_UINT64, .TYPE_INT32, .TYPE_FIXED64, .TYPE_FIXED32, .TYPE_BOOL, .TYPE_STRING, .TYPE_BYTES, .TYPE_UINT32, .TYPE_SFIXED32, .TYPE_SFIXED64, .TYPE_SINT32, .TYPE_SINT64 => true,
        else => false,
    };
}

fn isPlainScalarField(field: *const descriptor.FieldDescriptorProto) bool {
    if (field.label) |label| {
        if (label == .LABEL_REPEATED) return false;
    }
    if (field.oneof_index != null and field.proto3_optional != true) return false;
    const t = field.type orelse return false;
    return isScalarFieldType(t);
}

fn scalarMetadataName(t: FieldType) []const u8 {
    return switch (t) {
        .TYPE_DOUBLE => "double",
        .TYPE_FLOAT => "float",
        .TYPE_INT64 => "int64",
        .TYPE_UINT64 => "uint64",
        .TYPE_INT32 => "int32",
        .TYPE_FIXED64 => "fixed64",
        .TYPE_FIXED32 => "fixed32",
        .TYPE_BOOL => "bool",
        .TYPE_STRING => "string",
        .TYPE_BYTES => "bytes",
        .TYPE_UINT32 => "uint32",
        .TYPE_SFIXED32 => "sfixed32",
        .TYPE_SFIXED64 => "sfixed64",
        .TYPE_SINT32 => "sint32",
        .TYPE_SINT64 => "sint64",
        else => unreachable,
    };
}

fn scalarZigType(t: FieldType) []const u8 {
    return switch (t) {
        .TYPE_DOUBLE => "f64",
        .TYPE_FLOAT => "f32",
        .TYPE_INT64, .TYPE_SINT64, .TYPE_SFIXED64 => "i64",
        .TYPE_UINT64, .TYPE_FIXED64 => "u64",
        .TYPE_INT32, .TYPE_SINT32, .TYPE_SFIXED32 => "i32",
        .TYPE_UINT32, .TYPE_FIXED32 => "u32",
        .TYPE_BOOL => "bool",
        .TYPE_STRING, .TYPE_BYTES => "[]const u8",
        else => unreachable,
    };
}

fn scalarDefaultLiteral(t: FieldType) []const u8 {
    return switch (t) {
        .TYPE_DOUBLE, .TYPE_FLOAT => "0.0",
        .TYPE_INT64, .TYPE_SINT64, .TYPE_SFIXED64, .TYPE_UINT64, .TYPE_FIXED64, .TYPE_INT32, .TYPE_SINT32, .TYPE_SFIXED32, .TYPE_UINT32, .TYPE_FIXED32 => "0",
        .TYPE_BOOL => "false",
        .TYPE_STRING, .TYPE_BYTES => "\"\"",
        else => unreachable,
    };
}

fn escapeZigKeyword(alloc: std.mem.Allocator, name: []const u8) ![]u8 {
    if (std.zig.Token.keywords.has(name)) {
        return std.fmt.allocPrint(alloc, "@\"{s}\"", .{name});
    }
    return alloc.dupe(u8, name);
}

fn toCamelCase(alloc: std.mem.Allocator, snake: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .{};
    try out.ensureTotalCapacity(alloc, snake.len);
    var upper_next = true;
    for (snake) |c| {
        if (c == '_') {
            upper_next = true;
            continue;
        }
        try out.append(alloc, if (upper_next) std.ascii.toUpper(c) else c);
        upper_next = false;
    }
    return out.toOwnedSlice(alloc);
}
