const std = @import("std");
const descriptor = @import("gen/google/protobuf.pb.zig");
const protobuf = @import("our_protobuf");
const GeneratedFile = @import("generated_file.zig").GeneratedFile;

pub fn generateFile(
    alloc: std.mem.Allocator,
    desc_file: *const protobuf.DescFile,
    file_proto: *const descriptor.FileDescriptorProto,
) ![]u8 {
    var f = GeneratedFile.init(alloc);

    try f.writeLine("// Generated by protoc-gen-zig — DO NOT EDIT");
    try f.writeLine(.{ "// Source: ", desc_file.name });
    try f.emptyLine();

    // TODO make sure this is always correct
    if (desc_file.messages.len > 0) {
        try f.writeLine("const std = @import(\"std\");");
        try f.writeLine("const _codegen = @import(\"protobuf\")._codegen;");
        try f.writeLine("const _metadata = _codegen.metadata;");
        try f.emptyLine();
    }

    for (desc_file.messages) |*msg| {
        try generateMessage(&f, msg);
    }

    for (desc_file.enums) |*e| {
        try generateEnum(&f, e);
    }

    try f.emptyLine();
    try emitDescriptorBytes(&f, file_proto, alloc);

    const raw = try f.toOwnedSlice();
    defer alloc.free(raw);
    return try formatZigSource(alloc, raw);
}

fn formatZigSource(alloc: std.mem.Allocator, source: []const u8) ![]u8 {
    const source_z = try alloc.dupeZ(u8, source);
    defer alloc.free(source_z);
    var tree = try std.zig.Ast.parse(alloc, source_z, .zig);
    defer tree.deinit(alloc);
    if (tree.errors.len != 0) return error.GeneratedSourceHasParseErrors;
    return tree.renderAlloc(alloc);
}

fn generateMessage(
    f: *GeneratedFile,
    msg: *const protobuf.DescMessage,
) !void {
    // TODO escape directly local_name
    const safe_name = try escapeZigKeyword(f.alloc, msg.local_name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = struct {" });
    f.indent();

    // Plain scalar struct fields (scalar, not in a oneof).
    for (msg.fields) |*field| {
        if (field.kind != .scalar) continue;
        if (field.kind.scalar.oneof != null) continue;
        try generateField(f, field);
    }
    // Oneof union fields (synthetic proto3-optional oneofs are excluded from msg.oneofs).
    for (msg.oneofs) |*oneof| {
        try generateOneofField(f, oneof);
    }
    try f.emptyLine();

    for (msg.nested_messages) |*nested| {
        try generateMessage(f, nested);
    }

    for (msg.nested_enums) |*e| {
        try generateEnum(f, e);
    }

    // Plain scalar field getters.
    for (msg.fields) |*field| {
        if (field.kind != .scalar) continue;
        if (field.kind.scalar.oneof != null) continue;
        try generateFieldGetter(f, field);
    }
    // Oneof variant getters.
    for (msg.oneofs) |*oneof| {
        try generateOneofVariantGetters(f, oneof);
    }

    try f.emptyLine();
    try generateMessageDeinit(f);

    try f.emptyLine();
    try generateMessageMetadata(f, msg);

    f.unindent();
    try f.writeLine("};");

    try f.emptyLine();
}

fn generateEnum(
    f: *GeneratedFile,
    e: *const protobuf.DescEnum,
) !void {
    // TODO escape directly local_name
    const safe_name = try escapeZigKeyword(f.alloc, e.local_name);
    defer f.alloc.free(safe_name);

    try f.writeLine(.{ "pub const ", safe_name, " = enum(i32) {" });
    f.indent();

    for (e.values) |*v| {
        const safe_value_name = try escapeZigKeyword(f.alloc, v.local_name);
        defer f.alloc.free(safe_value_name);
        try f.writeLine(.{ safe_value_name, " = ", v.number, "," });
    }

    try f.writeLine("_,");

    f.unindent();
    try f.writeLine("};");
    try f.emptyLine();
}

fn generateMessageDeinit(f: *GeneratedFile) !void {
    try f.writeLine("pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {");
    f.indent();
    try f.writeLine("_codegen.deinit_message(self, allocator);");
    f.unindent();
    try f.writeLine("}");
}

fn generateMessageMetadata(
    f: *GeneratedFile,
    msg: *const protobuf.DescMessage,
) !void {
    try f.writeLine("pub const _desc = _metadata.MessageMetadata{");
    f.indent();
    try f.writeLine(".fields = &[_]_metadata.FieldMetadata{");
    f.indent();

    var field_index: u32 = 0;

    // Plain scalar fields (not in a oneof).
    for (msg.fields) |*field| {
        if (field.kind != .scalar) continue;
        if (field.kind.scalar.oneof != null) continue;
        try f.writeLine(.{
            ".{ .number = ",
            field.number,
            ", .field_index = ",
            field_index,
            ", .kind = .{ .scalar = .{ .scalar = .",
            @tagName(field.kind.scalar.scalar),
            " } } }, // ",
            field.name,
        });
        field_index += 1;
    }

    // Oneof variant entries — all variants of a group share the same field_index.
    for (msg.oneofs) |*oneof| {
        for (oneof.fields) |field_ptr| {
            if (field_ptr.kind != .scalar) continue;
            try f.writeLine(.{
                ".{ .number = ",
                field_ptr.number,
                ", .field_index = ",
                field_index,
                ", .oneof_variant = \"",
                field_ptr.name,
                "\", .kind = .{ .scalar = .{ .scalar = .",
                @tagName(field_ptr.kind.scalar.scalar),
                " } } }, // ",
                field_ptr.name,
            });
        }
        field_index += 1;
    }

    f.unindent();
    try f.writeLine("},");
    f.unindent();
    try f.writeLine("};");
}

fn generateField(
    f: *GeneratedFile,
    field: *const protobuf.DescField,
) !void {
    // field.local_name is already keyword-escaped by the descriptor builder.
    try f.writeLine(.{ field.local_name, ": ?", scalarZigType(field.kind.scalar.scalar), " = null," });
}

fn generateOneofField(
    f: *GeneratedFile,
    oneof: *const protobuf.DescOneof,
) !void {
    const safe_name = try escapeZigKeyword(f.alloc, oneof.local_name);
    defer f.alloc.free(safe_name);
    try f.write(.{ safe_name, ": ?union(enum) {" });
    for (oneof.fields) |field_ptr| {
        if (field_ptr.kind != .scalar) continue;
        // field_ptr.local_name is already keyword-escaped.
        try f.write(.{ " ", field_ptr.local_name, ": ", scalarZigType(field_ptr.kind.scalar.scalar), "," });
    }
    try f.writeLine(" } = null,");
}

fn generateOneofVariantGetters(
    f: *GeneratedFile,
    oneof: *const protobuf.DescOneof,
) !void {
    const safe_oneof_name = try escapeZigKeyword(f.alloc, oneof.local_name);
    defer f.alloc.free(safe_oneof_name);
    for (oneof.fields) |field_ptr| {
        if (field_ptr.kind != .scalar) continue;
        const getter_name = try toCamelCase(f.alloc, field_ptr.name);
        defer f.alloc.free(getter_name);
        const default = scalarDefaultLiteral(field_ptr.kind.scalar.scalar);
        try f.emptyLine();
        try f.writeLine(.{ "pub fn get", getter_name, "(self: @This()) ", scalarZigType(field_ptr.kind.scalar.scalar), " {" });
        f.indent();
        try f.writeLine(.{
            "return if (self.",   safe_oneof_name,       ") |c| switch (c) { .",
            field_ptr.local_name, " => |v| v, else => ", default,
            " } else ",           default,               ";",
        });
        f.unindent();
        try f.writeLine("}");
    }
}

fn generateFieldGetter(
    f: *GeneratedFile,
    field: *const protobuf.DescField,
) !void {
    // TODO make sure the new name doesn't conflict with any existing member
    const field_name_camel = try toCamelCase(f.alloc, field.name);
    defer f.alloc.free(field_name_camel);

    // field.local_name is already keyword-escaped.
    const zig_type = scalarZigType(field.kind.scalar.scalar);
    const default = scalarDefaultLiteral(field.kind.scalar.scalar);

    try f.emptyLine();
    try f.writeLine(.{ "pub fn get", field_name_camel, "(self: @This()) ", zig_type, " {" });
    f.indent();
    try f.writeLine(.{ "return self.", field.local_name, " orelse ", default, ";" });
    f.unindent();
    try f.writeLine("}");
}

fn scalarZigType(t: protobuf.ScalarType) []const u8 {
    return switch (t) {
        .double => "f64",
        .float => "f32",
        .int64, .sint64, .sfixed64 => "i64",
        .uint64, .fixed64 => "u64",
        .int32, .sint32, .sfixed32 => "i32",
        .uint32, .fixed32 => "u32",
        .bool => "bool",
        .string, .bytes => "[]const u8",
    };
}

fn scalarDefaultLiteral(t: protobuf.ScalarType) []const u8 {
    return switch (t) {
        .double, .float => "0.0",
        .int64, .sint64, .sfixed64, .uint64, .fixed64, .int32, .sint32, .sfixed32, .uint32, .fixed32 => "0",
        .bool => "false",
        .string, .bytes => "\"\"",
    };
}

pub fn escapeZigKeyword(alloc: std.mem.Allocator, name: []const u8) ![]u8 {
    if (std.zig.Token.keywords.has(name)) {
        return std.fmt.allocPrint(alloc, "@\"{s}\"", .{name});
    }
    return alloc.dupe(u8, name);
}

fn emitDescriptorBytes(
    f: *GeneratedFile,
    file: *const descriptor.FileDescriptorProto,
    alloc: std.mem.Allocator,
) !void {
    var w: std.Io.Writer.Allocating = .init(alloc);
    defer w.deinit();

    // Strip source_code_info before encoding
    var stripped = file.*;
    stripped.source_code_info = null;
    try stripped.encode(&w.writer, alloc);
    const bytes = w.written();

    // TODO: make sure variable name doesn't conflict with any existing identifier
    try f.write("pub const DESCRIPTOR_BYTES: []const u8 = \"");
    var buf: [4]u8 = undefined;
    for (bytes) |b| {
        const s = try std.fmt.bufPrint(&buf, "\\x{x:0>2}", .{b});
        try f.write(s);
    }
    try f.writeLine("\";");
}

pub fn toCamelCase(alloc: std.mem.Allocator, snake: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .{};
    try out.ensureTotalCapacity(alloc, snake.len);
    var upper_next = true;
    for (snake) |c| {
        if (c == '_') {
            upper_next = true;
            continue;
        }
        try out.append(alloc, if (upper_next) std.ascii.toUpper(c) else c);
        upper_next = false;
    }
    return out.toOwnedSlice(alloc);
}
