// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/any.proto

const _metadata = @import("protobuf")._metadata;

pub const Any = struct {
    type_url: ?[]const u8 = null,
    value: ?[]const u8 = null,

    pub fn getTypeUrl(self: @This()) []const u8 {
        return self.type_url orelse "";
    }

    pub fn getValue(self: @This()) []const u8 {
        return self.value orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // type_url
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bytes } } }, // value
        },
    };
};
