// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/any.proto

pub const Any = struct {
    type_url: ?[]const u8 = null,
    value: ?[]const u8 = null,

    pub fn getTypeUrl(self: @This()) []const u8 {
        return self.type_url orelse "";
    }

    pub fn getValue(self: @This()) []const u8 {
        return self.value orelse "";
    }
};
