// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/api.proto

const _metadata = @import("protobuf")._metadata;

pub const Api = struct {
    name: ?[]const u8 = null,
    version: ?[]const u8 = null,
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getVersion(self: @This()) []const u8 {
        return self.version orelse "";
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 4, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // version
            .{ .number = 8, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // edition
        },
    };
};

pub const Method = struct {
    name: ?[]const u8 = null,
    request_type_url: ?[]const u8 = null,
    request_streaming: ?bool = null,
    response_type_url: ?[]const u8 = null,
    response_streaming: ?bool = null,
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getRequestTypeUrl(self: @This()) []const u8 {
        return self.request_type_url orelse "";
    }

    pub fn getRequestStreaming(self: @This()) bool {
        return self.request_streaming orelse false;
    }

    pub fn getResponseTypeUrl(self: @This()) []const u8 {
        return self.response_type_url orelse "";
    }

    pub fn getResponseStreaming(self: @This()) bool {
        return self.response_streaming orelse false;
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // request_type_url
            .{ .number = 3, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // request_streaming
            .{ .number = 4, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .string } } }, // response_type_url
            .{ .number = 5, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // response_streaming
            .{ .number = 8, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .string } } }, // edition
        },
    };
};

pub const Mixin = struct {
    name: ?[]const u8 = null,
    root: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getRoot(self: @This()) []const u8 {
        return self.root orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // root
        },
    };
};
