// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/api.proto

pub const Api = struct {
    name: ?[]const u8 = null,
    // field methods
    // field options
    version: ?[]const u8 = null,
    // field source_context
    // field mixins
    // field syntax
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getVersion(self: @This()) []const u8 {
        return self.version orelse "";
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }
};

pub const Method = struct {
    name: ?[]const u8 = null,
    request_type_url: ?[]const u8 = null,
    request_streaming: ?bool = null,
    response_type_url: ?[]const u8 = null,
    response_streaming: ?bool = null,
    // field options
    // field syntax
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getRequestTypeUrl(self: @This()) []const u8 {
        return self.request_type_url orelse "";
    }

    pub fn getRequestStreaming(self: @This()) bool {
        return self.request_streaming orelse false;
    }

    pub fn getResponseTypeUrl(self: @This()) []const u8 {
        return self.response_type_url orelse "";
    }

    pub fn getResponseStreaming(self: @This()) bool {
        return self.response_streaming orelse false;
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }
};

pub const Mixin = struct {
    name: ?[]const u8 = null,
    root: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getRoot(self: @This()) []const u8 {
        return self.root orelse "";
    }
};
