// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/cpp_features.proto

const _metadata = @import("protobuf")._metadata;

pub const CppFeatures = struct {
    legacy_closed_enum: ?bool = null,
    // field string_type
    enum_name_uses_string_view: ?bool = null,

    pub const StringType = enum(i32) {
        STRING_TYPE_UNKNOWN = 0,
        VIEW = 1,
        CORD = 2,
        STRING = 3,
        _,
    };

    pub fn getLegacyClosedEnum(self: @This()) bool {
        return self.legacy_closed_enum orelse false;
    }

    pub fn getEnumNameUsesStringView(self: @This()) bool {
        return self.enum_name_uses_string_view orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // legacy_closed_enum
            .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // enum_name_uses_string_view
        },
    };
};
