// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/cpp_features.proto

pub const CppFeatures = struct {
    legacy_closed_enum: ?bool = null,
    // field string_type
    enum_name_uses_string_view: ?bool = null,

    pub const StringType = enum(i32) {
        STRING_TYPE_UNKNOWN = 0,
        VIEW = 1,
        CORD = 2,
        STRING = 3,
        _,
    };

    pub fn getLegacyClosedEnum(self: @This()) bool {
        return self.legacy_closed_enum orelse false;
    }

    pub fn getEnumNameUsesStringView(self: @This()) bool {
        return self.enum_name_uses_string_view orelse false;
    }
};
