// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/descriptor.proto

const _metadata = @import("protobuf")._metadata;

pub const FileDescriptorSet = struct {
    // field file

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const FileDescriptorProto = struct {
    name: ?[]const u8 = null,
    package: ?[]const u8 = null,
    // field dependency
    // field public_dependency
    // field weak_dependency
    // field option_dependency
    // field message_type
    // field enum_type
    // field service
    // field extension
    // field options
    // field source_code_info
    syntax: ?[]const u8 = null,
    // field edition

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getPackage(self: @This()) []const u8 {
        return self.package orelse "";
    }

    pub fn getSyntax(self: @This()) []const u8 {
        return self.syntax orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // package
            .{ .number = 12, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // syntax
        },
    };
};

pub const DescriptorProto = struct {
    name: ?[]const u8 = null,
    // field field
    // field extension
    // field nested_type
    // field enum_type
    // field extension_range
    // field oneof_decl
    // field options
    // field reserved_range
    // field reserved_name
    // field visibility

    pub const ExtensionRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,
        // field options

        pub fn getStart(self: @This()) i32 {
            return self.start orelse 0;
        }

        pub fn getEnd(self: @This()) i32 {
            return self.end orelse 0;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // start
                .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // end
            },
        };
    };

    pub const ReservedRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,

        pub fn getStart(self: @This()) i32 {
            return self.start orelse 0;
        }

        pub fn getEnd(self: @This()) i32 {
            return self.end orelse 0;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // start
                .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // end
            },
        };
    };

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
        },
    };
};

pub const ExtensionRangeOptions = struct {
    // field uninterpreted_option
    // field declaration
    // field features
    // field verification

    pub const Declaration = struct {
        number: ?i32 = null,
        full_name: ?[]const u8 = null,
        type: ?[]const u8 = null,
        reserved: ?bool = null,
        repeated: ?bool = null,

        pub fn getNumber(self: @This()) i32 {
            return self.number orelse 0;
        }

        pub fn getFullName(self: @This()) []const u8 {
            return self.full_name orelse "";
        }

        pub fn getType(self: @This()) []const u8 {
            return self.type orelse "";
        }

        pub fn getReserved(self: @This()) bool {
            return self.reserved orelse false;
        }

        pub fn getRepeated(self: @This()) bool {
            return self.repeated orelse false;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // number
                .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // full_name
                .{ .number = 3, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // type
                .{ .number = 5, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .bool } } }, // reserved
                .{ .number = 6, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // repeated
            },
        };
    };

    pub const VerificationState = enum(i32) {
        DECLARATION = 0,
        UNVERIFIED = 1,
        _,
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const FieldDescriptorProto = struct {
    name: ?[]const u8 = null,
    number: ?i32 = null,
    // field label
    // field type
    type_name: ?[]const u8 = null,
    extendee: ?[]const u8 = null,
    default_value: ?[]const u8 = null,
    oneof_index: ?i32 = null,
    json_name: ?[]const u8 = null,
    // field options
    proto3_optional: ?bool = null,

    pub const Type = enum(i32) {
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
        _,
    };

    pub const Label = enum(i32) {
        LABEL_OPTIONAL = 1,
        LABEL_REPEATED = 3,
        LABEL_REQUIRED = 2,
        _,
    };

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getNumber(self: @This()) i32 {
        return self.number orelse 0;
    }

    pub fn getTypeName(self: @This()) []const u8 {
        return self.type_name orelse "";
    }

    pub fn getExtendee(self: @This()) []const u8 {
        return self.extendee orelse "";
    }

    pub fn getDefaultValue(self: @This()) []const u8 {
        return self.default_value orelse "";
    }

    pub fn getOneofIndex(self: @This()) i32 {
        return self.oneof_index orelse 0;
    }

    pub fn getJsonName(self: @This()) []const u8 {
        return self.json_name orelse "";
    }

    pub fn getProto3Optional(self: @This()) bool {
        return self.proto3_optional orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // number
            .{ .number = 6, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // type_name
            .{ .number = 2, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .string } } }, // extendee
            .{ .number = 7, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .string } } }, // default_value
            .{ .number = 9, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // oneof_index
            .{ .number = 10, .field_index = 6, .kind = .{ .scalar = .{ .scalar = .string } } }, // json_name
            .{ .number = 17, .field_index = 7, .kind = .{ .scalar = .{ .scalar = .bool } } }, // proto3_optional
        },
    };
};

pub const OneofDescriptorProto = struct {
    name: ?[]const u8 = null,
    // field options

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
        },
    };
};

pub const EnumDescriptorProto = struct {
    name: ?[]const u8 = null,
    // field value
    // field options
    // field reserved_range
    // field reserved_name
    // field visibility

    pub const EnumReservedRange = struct {
        start: ?i32 = null,
        end: ?i32 = null,

        pub fn getStart(self: @This()) i32 {
            return self.start orelse 0;
        }

        pub fn getEnd(self: @This()) i32 {
            return self.end orelse 0;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // start
                .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // end
            },
        };
    };

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
        },
    };
};

pub const EnumValueDescriptorProto = struct {
    name: ?[]const u8 = null,
    number: ?i32 = null,
    // field options

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getNumber(self: @This()) i32 {
        return self.number orelse 0;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // number
        },
    };
};

pub const ServiceDescriptorProto = struct {
    name: ?[]const u8 = null,
    // field method
    // field options

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
        },
    };
};

pub const MethodDescriptorProto = struct {
    name: ?[]const u8 = null,
    input_type: ?[]const u8 = null,
    output_type: ?[]const u8 = null,
    // field options
    client_streaming: ?bool = null,
    server_streaming: ?bool = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getInputType(self: @This()) []const u8 {
        return self.input_type orelse "";
    }

    pub fn getOutputType(self: @This()) []const u8 {
        return self.output_type orelse "";
    }

    pub fn getClientStreaming(self: @This()) bool {
        return self.client_streaming orelse false;
    }

    pub fn getServerStreaming(self: @This()) bool {
        return self.server_streaming orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // input_type
            .{ .number = 3, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // output_type
            .{ .number = 5, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .bool } } }, // client_streaming
            .{ .number = 6, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // server_streaming
        },
    };
};

pub const FileOptions = struct {
    java_package: ?[]const u8 = null,
    java_outer_classname: ?[]const u8 = null,
    java_multiple_files: ?bool = null,
    java_generate_equals_and_hash: ?bool = null,
    java_string_check_utf8: ?bool = null,
    // field optimize_for
    go_package: ?[]const u8 = null,
    cc_generic_services: ?bool = null,
    java_generic_services: ?bool = null,
    py_generic_services: ?bool = null,
    deprecated: ?bool = null,
    cc_enable_arenas: ?bool = null,
    objc_class_prefix: ?[]const u8 = null,
    csharp_namespace: ?[]const u8 = null,
    swift_prefix: ?[]const u8 = null,
    php_class_prefix: ?[]const u8 = null,
    php_namespace: ?[]const u8 = null,
    php_metadata_namespace: ?[]const u8 = null,
    ruby_package: ?[]const u8 = null,
    // field features
    // field uninterpreted_option

    pub const OptimizeMode = enum(i32) {
        SPEED = 1,
        CODE_SIZE = 2,
        LITE_RUNTIME = 3,
        _,
    };

    pub fn getJavaPackage(self: @This()) []const u8 {
        return self.java_package orelse "";
    }

    pub fn getJavaOuterClassname(self: @This()) []const u8 {
        return self.java_outer_classname orelse "";
    }

    pub fn getJavaMultipleFiles(self: @This()) bool {
        return self.java_multiple_files orelse false;
    }

    pub fn getJavaGenerateEqualsAndHash(self: @This()) bool {
        return self.java_generate_equals_and_hash orelse false;
    }

    pub fn getJavaStringCheckUtf8(self: @This()) bool {
        return self.java_string_check_utf8 orelse false;
    }

    pub fn getGoPackage(self: @This()) []const u8 {
        return self.go_package orelse "";
    }

    pub fn getCcGenericServices(self: @This()) bool {
        return self.cc_generic_services orelse false;
    }

    pub fn getJavaGenericServices(self: @This()) bool {
        return self.java_generic_services orelse false;
    }

    pub fn getPyGenericServices(self: @This()) bool {
        return self.py_generic_services orelse false;
    }

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub fn getCcEnableArenas(self: @This()) bool {
        return self.cc_enable_arenas orelse false;
    }

    pub fn getObjcClassPrefix(self: @This()) []const u8 {
        return self.objc_class_prefix orelse "";
    }

    pub fn getCsharpNamespace(self: @This()) []const u8 {
        return self.csharp_namespace orelse "";
    }

    pub fn getSwiftPrefix(self: @This()) []const u8 {
        return self.swift_prefix orelse "";
    }

    pub fn getPhpClassPrefix(self: @This()) []const u8 {
        return self.php_class_prefix orelse "";
    }

    pub fn getPhpNamespace(self: @This()) []const u8 {
        return self.php_namespace orelse "";
    }

    pub fn getPhpMetadataNamespace(self: @This()) []const u8 {
        return self.php_metadata_namespace orelse "";
    }

    pub fn getRubyPackage(self: @This()) []const u8 {
        return self.ruby_package orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // java_package
            .{ .number = 8, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // java_outer_classname
            .{ .number = 10, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // java_multiple_files
            .{ .number = 20, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .bool } } }, // java_generate_equals_and_hash
            .{ .number = 27, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // java_string_check_utf8
            .{ .number = 11, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .string } } }, // go_package
            .{ .number = 16, .field_index = 6, .kind = .{ .scalar = .{ .scalar = .bool } } }, // cc_generic_services
            .{ .number = 17, .field_index = 7, .kind = .{ .scalar = .{ .scalar = .bool } } }, // java_generic_services
            .{ .number = 18, .field_index = 8, .kind = .{ .scalar = .{ .scalar = .bool } } }, // py_generic_services
            .{ .number = 23, .field_index = 9, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
            .{ .number = 31, .field_index = 10, .kind = .{ .scalar = .{ .scalar = .bool } } }, // cc_enable_arenas
            .{ .number = 36, .field_index = 11, .kind = .{ .scalar = .{ .scalar = .string } } }, // objc_class_prefix
            .{ .number = 37, .field_index = 12, .kind = .{ .scalar = .{ .scalar = .string } } }, // csharp_namespace
            .{ .number = 39, .field_index = 13, .kind = .{ .scalar = .{ .scalar = .string } } }, // swift_prefix
            .{ .number = 40, .field_index = 14, .kind = .{ .scalar = .{ .scalar = .string } } }, // php_class_prefix
            .{ .number = 41, .field_index = 15, .kind = .{ .scalar = .{ .scalar = .string } } }, // php_namespace
            .{ .number = 44, .field_index = 16, .kind = .{ .scalar = .{ .scalar = .string } } }, // php_metadata_namespace
            .{ .number = 45, .field_index = 17, .kind = .{ .scalar = .{ .scalar = .string } } }, // ruby_package
        },
    };
};

pub const MessageOptions = struct {
    message_set_wire_format: ?bool = null,
    no_standard_descriptor_accessor: ?bool = null,
    deprecated: ?bool = null,
    map_entry: ?bool = null,
    deprecated_legacy_json_field_conflicts: ?bool = null,
    // field features
    // field uninterpreted_option

    pub fn getMessageSetWireFormat(self: @This()) bool {
        return self.message_set_wire_format orelse false;
    }

    pub fn getNoStandardDescriptorAccessor(self: @This()) bool {
        return self.no_standard_descriptor_accessor orelse false;
    }

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub fn getMapEntry(self: @This()) bool {
        return self.map_entry orelse false;
    }

    pub fn getDeprecatedLegacyJsonFieldConflicts(self: @This()) bool {
        return self.deprecated_legacy_json_field_conflicts orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // message_set_wire_format
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // no_standard_descriptor_accessor
            .{ .number = 3, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
            .{ .number = 7, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .bool } } }, // map_entry
            .{ .number = 11, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated_legacy_json_field_conflicts
        },
    };
};

pub const FieldOptions = struct {
    // field ctype
    @"packed": ?bool = null,
    // field jstype
    lazy: ?bool = null,
    unverified_lazy: ?bool = null,
    deprecated: ?bool = null,
    weak: ?bool = null,
    debug_redact: ?bool = null,
    // field retention
    // field targets
    // field edition_defaults
    // field features
    // field feature_support
    // field uninterpreted_option

    pub const EditionDefault = struct {
        // field edition
        value: ?[]const u8 = null,

        pub fn getValue(self: @This()) []const u8 {
            return self.value orelse "";
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 2, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // value
            },
        };
    };

    pub const FeatureSupport = struct {
        // field edition_introduced
        // field edition_deprecated
        deprecation_warning: ?[]const u8 = null,
        // field edition_removed

        pub fn getDeprecationWarning(self: @This()) []const u8 {
            return self.deprecation_warning orelse "";
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 3, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // deprecation_warning
            },
        };
    };

    pub const CType = enum(i32) {
        STRING = 0,
        CORD = 1,
        STRING_PIECE = 2,
        _,
    };

    pub const JSType = enum(i32) {
        JS_NORMAL = 0,
        JS_STRING = 1,
        JS_NUMBER = 2,
        _,
    };

    pub const OptionRetention = enum(i32) {
        RETENTION_UNKNOWN = 0,
        RETENTION_RUNTIME = 1,
        RETENTION_SOURCE = 2,
        _,
    };

    pub const OptionTargetType = enum(i32) {
        TARGET_TYPE_UNKNOWN = 0,
        TARGET_TYPE_FILE = 1,
        TARGET_TYPE_EXTENSION_RANGE = 2,
        TARGET_TYPE_MESSAGE = 3,
        TARGET_TYPE_FIELD = 4,
        TARGET_TYPE_ONEOF = 5,
        TARGET_TYPE_ENUM = 6,
        TARGET_TYPE_ENUM_ENTRY = 7,
        TARGET_TYPE_SERVICE = 8,
        TARGET_TYPE_METHOD = 9,
        _,
    };

    pub fn getPacked(self: @This()) bool {
        return self.@"packed" orelse false;
    }

    pub fn getLazy(self: @This()) bool {
        return self.lazy orelse false;
    }

    pub fn getUnverifiedLazy(self: @This()) bool {
        return self.unverified_lazy orelse false;
    }

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub fn getWeak(self: @This()) bool {
        return self.weak orelse false;
    }

    pub fn getDebugRedact(self: @This()) bool {
        return self.debug_redact orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 2, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // packed
            .{ .number = 5, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // lazy
            .{ .number = 15, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // unverified_lazy
            .{ .number = 3, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
            .{ .number = 10, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // weak
            .{ .number = 16, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .bool } } }, // debug_redact
        },
    };
};

pub const OneofOptions = struct {
    // field features
    // field uninterpreted_option

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const EnumOptions = struct {
    allow_alias: ?bool = null,
    deprecated: ?bool = null,
    deprecated_legacy_json_field_conflicts: ?bool = null,
    // field features
    // field uninterpreted_option

    pub fn getAllowAlias(self: @This()) bool {
        return self.allow_alias orelse false;
    }

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub fn getDeprecatedLegacyJsonFieldConflicts(self: @This()) bool {
        return self.deprecated_legacy_json_field_conflicts orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 2, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // allow_alias
            .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
            .{ .number = 6, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated_legacy_json_field_conflicts
        },
    };
};

pub const EnumValueOptions = struct {
    deprecated: ?bool = null,
    // field features
    debug_redact: ?bool = null,
    // field feature_support
    // field uninterpreted_option

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub fn getDebugRedact(self: @This()) bool {
        return self.debug_redact orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
            .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // debug_redact
        },
    };
};

pub const ServiceOptions = struct {
    // field features
    deprecated: ?bool = null,
    // field uninterpreted_option

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 33, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
        },
    };
};

pub const MethodOptions = struct {
    deprecated: ?bool = null,
    // field idempotency_level
    // field features
    // field uninterpreted_option

    pub const IdempotencyLevel = enum(i32) {
        IDEMPOTENCY_UNKNOWN = 0,
        NO_SIDE_EFFECTS = 1,
        IDEMPOTENT = 2,
        _,
    };

    pub fn getDeprecated(self: @This()) bool {
        return self.deprecated orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 33, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // deprecated
        },
    };
};

pub const UninterpretedOption = struct {
    // field name
    identifier_value: ?[]const u8 = null,
    positive_int_value: ?u64 = null,
    negative_int_value: ?i64 = null,
    double_value: ?f64 = null,
    string_value: ?[]const u8 = null,
    aggregate_value: ?[]const u8 = null,

    pub const NamePart = struct {
        name_part: ?[]const u8 = null,
        is_extension: ?bool = null,

        pub fn getNamePart(self: @This()) []const u8 {
            return self.name_part orelse "";
        }

        pub fn getIsExtension(self: @This()) bool {
            return self.is_extension orelse false;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name_part
                .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // is_extension
            },
        };
    };

    pub fn getIdentifierValue(self: @This()) []const u8 {
        return self.identifier_value orelse "";
    }

    pub fn getPositiveIntValue(self: @This()) u64 {
        return self.positive_int_value orelse 0;
    }

    pub fn getNegativeIntValue(self: @This()) i64 {
        return self.negative_int_value orelse 0;
    }

    pub fn getDoubleValue(self: @This()) f64 {
        return self.double_value orelse 0.0;
    }

    pub fn getStringValue(self: @This()) []const u8 {
        return self.string_value orelse "";
    }

    pub fn getAggregateValue(self: @This()) []const u8 {
        return self.aggregate_value orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 3, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // identifier_value
            .{ .number = 4, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .uint64 } } }, // positive_int_value
            .{ .number = 5, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .int64 } } }, // negative_int_value
            .{ .number = 6, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .double } } }, // double_value
            .{ .number = 7, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bytes } } }, // string_value
            .{ .number = 8, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .string } } }, // aggregate_value
        },
    };
};

pub const FeatureSet = struct {
    // field field_presence
    // field enum_type
    // field repeated_field_encoding
    // field utf8_validation
    // field message_encoding
    // field json_format
    // field enforce_naming_style
    // field default_symbol_visibility

    pub const VisibilityFeature = struct {
        pub const DefaultSymbolVisibility = enum(i32) {
            DEFAULT_SYMBOL_VISIBILITY_UNKNOWN = 0,
            EXPORT_ALL = 1,
            EXPORT_TOP_LEVEL = 2,
            LOCAL_ALL = 3,
            STRICT = 4,
            _,
        };

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{},
        };
    };

    pub const FieldPresence = enum(i32) {
        FIELD_PRESENCE_UNKNOWN = 0,
        EXPLICIT = 1,
        IMPLICIT = 2,
        LEGACY_REQUIRED = 3,
        _,
    };

    pub const EnumType = enum(i32) {
        ENUM_TYPE_UNKNOWN = 0,
        OPEN = 1,
        CLOSED = 2,
        _,
    };

    pub const RepeatedFieldEncoding = enum(i32) {
        REPEATED_FIELD_ENCODING_UNKNOWN = 0,
        PACKED = 1,
        EXPANDED = 2,
        _,
    };

    pub const Utf8Validation = enum(i32) {
        UTF8_VALIDATION_UNKNOWN = 0,
        VERIFY = 2,
        NONE = 3,
        _,
    };

    pub const MessageEncoding = enum(i32) {
        MESSAGE_ENCODING_UNKNOWN = 0,
        LENGTH_PREFIXED = 1,
        DELIMITED = 2,
        _,
    };

    pub const JsonFormat = enum(i32) {
        JSON_FORMAT_UNKNOWN = 0,
        ALLOW = 1,
        LEGACY_BEST_EFFORT = 2,
        _,
    };

    pub const EnforceNamingStyle = enum(i32) {
        ENFORCE_NAMING_STYLE_UNKNOWN = 0,
        STYLE2024 = 1,
        STYLE_LEGACY = 2,
        _,
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const FeatureSetDefaults = struct {
    // field defaults
    // field minimum_edition
    // field maximum_edition

    pub const FeatureSetEditionDefault = struct {
        // field edition
        // field overridable_features
        // field fixed_features

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{},
        };
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const SourceCodeInfo = struct {
    // field location

    pub const Location = struct {
        // field path
        // field span
        leading_comments: ?[]const u8 = null,
        trailing_comments: ?[]const u8 = null,
        // field leading_detached_comments

        pub fn getLeadingComments(self: @This()) []const u8 {
            return self.leading_comments orelse "";
        }

        pub fn getTrailingComments(self: @This()) []const u8 {
            return self.trailing_comments orelse "";
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 3, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // leading_comments
                .{ .number = 4, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // trailing_comments
            },
        };
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const GeneratedCodeInfo = struct {
    // field annotation

    pub const Annotation = struct {
        // field path
        source_file: ?[]const u8 = null,
        begin: ?i32 = null,
        end: ?i32 = null,
        // field semantic

        pub const Semantic = enum(i32) {
            NONE = 0,
            SET = 1,
            ALIAS = 2,
            _,
        };

        pub fn getSourceFile(self: @This()) []const u8 {
            return self.source_file orelse "";
        }

        pub fn getBegin(self: @This()) i32 {
            return self.begin orelse 0;
        }

        pub fn getEnd(self: @This()) i32 {
            return self.end orelse 0;
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 2, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // source_file
                .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // begin
                .{ .number = 4, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // end
            },
        };
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const Edition = enum(i32) {
    EDITION_UNKNOWN = 0,
    EDITION_LEGACY = 900,
    EDITION_PROTO2 = 998,
    EDITION_PROTO3 = 999,
    EDITION_2023 = 1000,
    EDITION_2024 = 1001,
    EDITION_UNSTABLE = 9999,
    EDITION_1_TEST_ONLY = 1,
    EDITION_2_TEST_ONLY = 2,
    EDITION_99997_TEST_ONLY = 99997,
    EDITION_99998_TEST_ONLY = 99998,
    EDITION_99999_TEST_ONLY = 99999,
    EDITION_MAX = 2147483647,
    _,
};

pub const SymbolVisibility = enum(i32) {
    VISIBILITY_UNSET = 0,
    VISIBILITY_LOCAL = 1,
    VISIBILITY_EXPORT = 2,
    _,
};
