// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/duration.proto

pub const Duration = struct {
    seconds: ?i64 = null,
    nanos: ?i32 = null,

    pub fn getSeconds(self: @This()) i64 {
        return self.seconds orelse 0;
    }

    pub fn getNanos(self: @This()) i32 {
        return self.nanos orelse 0;
    }
};
