// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/empty.proto

const _metadata = @import("protobuf")._metadata;

pub const Empty = struct {
    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};
