// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/field_mask.proto

const _metadata = @import("protobuf")._metadata;

pub const FieldMask = struct {
    // field paths

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};
