// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/go_features.proto

pub const GoFeatures = struct {
    legacy_unmarshal_json_enum: ?bool = null,
    // field api_level
    // field strip_enum_prefix

    pub const APILevel = enum(i32) {
        API_LEVEL_UNSPECIFIED = 0,
        API_OPEN = 1,
        API_HYBRID = 2,
        API_OPAQUE = 3,
        _,
    };

    pub const StripEnumPrefix = enum(i32) {
        STRIP_ENUM_PREFIX_UNSPECIFIED = 0,
        STRIP_ENUM_PREFIX_KEEP = 1,
        STRIP_ENUM_PREFIX_GENERATE_BOTH = 2,
        STRIP_ENUM_PREFIX_STRIP = 3,
        _,
    };

    pub fn getLegacyUnmarshalJsonEnum(self: @This()) bool {
        return self.legacy_unmarshal_json_enum orelse false;
    }
};
