// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/java_features.proto

pub const JavaFeatures = struct {
    legacy_closed_enum: ?bool = null,
    // field utf8_validation
    large_enum: ?bool = null,
    use_old_outer_classname_default: ?bool = null,
    // field nest_in_file_class

    pub const NestInFileClassFeature = struct {
        pub const NestInFileClass = enum(i32) {
            NEST_IN_FILE_CLASS_UNKNOWN = 0,
            NO = 1,
            YES = 2,
            LEGACY = 3,
            _,
        };
    };

    pub const Utf8Validation = enum(i32) {
        UTF8_VALIDATION_UNKNOWN = 0,
        DEFAULT = 1,
        VERIFY = 2,
        _,
    };

    pub fn getLegacyClosedEnum(self: @This()) bool {
        return self.legacy_closed_enum orelse false;
    }

    pub fn getLargeEnum(self: @This()) bool {
        return self.large_enum orelse false;
    }

    pub fn getUseOldOuterClassnameDefault(self: @This()) bool {
        return self.use_old_outer_classname_default orelse false;
    }
};
