// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/java_features.proto

const _metadata = @import("protobuf")._metadata;

pub const JavaFeatures = struct {
    legacy_closed_enum: ?bool = null,
    large_enum: ?bool = null,
    use_old_outer_classname_default: ?bool = null,

    pub const NestInFileClassFeature = struct {
        pub const NestInFileClass = enum(i32) {
            NEST_IN_FILE_CLASS_UNKNOWN = 0,
            NO = 1,
            YES = 2,
            LEGACY = 3,
            _,
        };

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{},
        };
    };

    pub const Utf8Validation = enum(i32) {
        UTF8_VALIDATION_UNKNOWN = 0,
        DEFAULT = 1,
        VERIFY = 2,
        _,
    };

    pub fn getLegacyClosedEnum(self: @This()) bool {
        return self.legacy_closed_enum orelse false;
    }

    pub fn getLargeEnum(self: @This()) bool {
        return self.large_enum orelse false;
    }

    pub fn getUseOldOuterClassnameDefault(self: @This()) bool {
        return self.use_old_outer_classname_default orelse false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .bool } } }, // legacy_closed_enum
            .{ .number = 3, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .bool } } }, // large_enum
            .{ .number = 4, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .bool } } }, // use_old_outer_classname_default
        },
    };
};
