// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/source_context.proto

pub const SourceContext = struct {
    file_name: ?[]const u8 = null,

    pub fn getFileName(self: @This()) []const u8 {
        return self.file_name orelse "";
    }
};
