// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/source_context.proto

const _metadata = @import("protobuf")._metadata;

pub const SourceContext = struct {
    file_name: ?[]const u8 = null,

    pub fn getFileName(self: @This()) []const u8 {
        return self.file_name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // file_name
        },
    };
};
