// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/struct.proto

const _metadata = @import("protobuf")._metadata;

pub const Struct = struct {
    pub const FieldsEntry = struct {
        key: ?[]const u8 = null,

        pub fn getKey(self: @This()) []const u8 {
            return self.key orelse "";
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // key
            },
        };
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const Value = struct {
    kind: ?union(enum) {
        number_value: f64,
        string_value: []const u8,
        bool_value: bool,
    } = null,

    pub fn getNumberValue(self: @This()) f64 {
        return if (self.kind) |c| switch (c) {
            .number_value => |v| v,
            else => 0.0,
        } else 0.0;
    }

    pub fn getStringValue(self: @This()) []const u8 {
        return if (self.kind) |c| switch (c) {
            .string_value => |v| v,
            else => "",
        } else "";
    }

    pub fn getBoolValue(self: @This()) bool {
        return if (self.kind) |c| switch (c) {
            .bool_value => |v| v,
            else => false,
        } else false;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 2, .field_index = 0, .oneof_variant = "number_value", .kind = .{ .scalar = .{ .scalar = .double } } }, // number_value
            .{ .number = 3, .field_index = 0, .oneof_variant = "string_value", .kind = .{ .scalar = .{ .scalar = .string } } }, // string_value
            .{ .number = 4, .field_index = 0, .oneof_variant = "bool_value", .kind = .{ .scalar = .{ .scalar = .bool } } }, // bool_value
        },
    };
};

pub const ListValue = struct {
    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const NullValue = enum(i32) {
    NULL_VALUE = 0,
    _,
};
