// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/struct.proto

const _metadata = @import("protobuf")._metadata;

pub const Struct = struct {
    // field fields

    pub const FieldsEntry = struct {
        key: ?[]const u8 = null,
        // field value

        pub fn getKey(self: @This()) []const u8 {
            return self.key orelse "";
        }

        pub const _desc = _metadata.MessageMetadata{
            .fields = &[_]_metadata.FieldMetadata{
                .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // key
            },
        };
    };

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const Value = struct {
    // field null_value
    // field number_value
    // field string_value
    // field bool_value
    // field struct_value
    // field list_value

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const ListValue = struct {
    // field values

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{},
    };
};

pub const NullValue = enum(i32) {
    NULL_VALUE = 0,
    _,
};
