// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/timestamp.proto

const _metadata = @import("protobuf")._metadata;

pub const Timestamp = struct {
    seconds: ?i64 = null,
    nanos: ?i32 = null,

    pub fn getSeconds(self: @This()) i64 {
        return self.seconds orelse 0;
    }

    pub fn getNanos(self: @This()) i32 {
        return self.nanos orelse 0;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int64 } } }, // seconds
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // nanos
        },
    };
};
