// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/type.proto

const _metadata = @import("protobuf")._metadata;

pub const Type = struct {
    name: ?[]const u8 = null,
    // field fields
    // field oneofs
    // field options
    // field source_context
    // field syntax
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 7, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // edition
        },
    };
};

pub const Field = struct {
    // field kind
    // field cardinality
    number: ?i32 = null,
    name: ?[]const u8 = null,
    type_url: ?[]const u8 = null,
    oneof_index: ?i32 = null,
    @"packed": ?bool = null,
    // field options
    json_name: ?[]const u8 = null,
    default_value: ?[]const u8 = null,

    pub const Kind = enum(i32) {
        TYPE_UNKNOWN = 0,
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
        _,
    };

    pub const Cardinality = enum(i32) {
        CARDINALITY_UNKNOWN = 0,
        CARDINALITY_OPTIONAL = 1,
        CARDINALITY_REQUIRED = 2,
        CARDINALITY_REPEATED = 3,
        _,
    };

    pub fn getNumber(self: @This()) i32 {
        return self.number orelse 0;
    }

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getTypeUrl(self: @This()) []const u8 {
        return self.type_url orelse "";
    }

    pub fn getOneofIndex(self: @This()) i32 {
        return self.oneof_index orelse 0;
    }

    pub fn getPacked(self: @This()) bool {
        return self.@"packed" orelse false;
    }

    pub fn getJsonName(self: @This()) []const u8 {
        return self.json_name orelse "";
    }

    pub fn getDefaultValue(self: @This()) []const u8 {
        return self.default_value orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 3, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // number
            .{ .number = 4, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 6, .field_index = 2, .kind = .{ .scalar = .{ .scalar = .string } } }, // type_url
            .{ .number = 7, .field_index = 3, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // oneof_index
            .{ .number = 8, .field_index = 4, .kind = .{ .scalar = .{ .scalar = .bool } } }, // packed
            .{ .number = 10, .field_index = 5, .kind = .{ .scalar = .{ .scalar = .string } } }, // json_name
            .{ .number = 11, .field_index = 6, .kind = .{ .scalar = .{ .scalar = .string } } }, // default_value
        },
    };
};

pub const Enum = struct {
    name: ?[]const u8 = null,
    // field enumvalue
    // field options
    // field source_context
    // field syntax
    edition: ?[]const u8 = null,

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getEdition(self: @This()) []const u8 {
        return self.edition orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 6, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .string } } }, // edition
        },
    };
};

pub const EnumValue = struct {
    name: ?[]const u8 = null,
    number: ?i32 = null,
    // field options

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub fn getNumber(self: @This()) i32 {
        return self.number orelse 0;
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
            .{ .number = 2, .field_index = 1, .kind = .{ .scalar = .{ .scalar = .int32 } } }, // number
        },
    };
};

pub const Option = struct {
    name: ?[]const u8 = null,
    // field value

    pub fn getName(self: @This()) []const u8 {
        return self.name orelse "";
    }

    pub const _desc = _metadata.MessageMetadata{
        .fields = &[_]_metadata.FieldMetadata{
            .{ .number = 1, .field_index = 0, .kind = .{ .scalar = .{ .scalar = .string } } }, // name
        },
    };
};

pub const Syntax = enum(i32) {
    SYNTAX_PROTO2 = 0,
    SYNTAX_PROTO3 = 1,
    SYNTAX_EDITIONS = 2,
    _,
};
