// Generated by protoc-gen-zig — DO NOT EDIT
// Source: google/protobuf/wrappers.proto

pub const DoubleValue = struct {
    value: ?f64 = null,

    pub fn getValue(self: @This()) f64 {
        return self.value orelse 0.0;
    }
};

pub const FloatValue = struct {
    value: ?f32 = null,

    pub fn getValue(self: @This()) f32 {
        return self.value orelse 0.0;
    }
};

pub const Int64Value = struct {
    value: ?i64 = null,

    pub fn getValue(self: @This()) i64 {
        return self.value orelse 0;
    }
};

pub const UInt64Value = struct {
    value: ?u64 = null,

    pub fn getValue(self: @This()) u64 {
        return self.value orelse 0;
    }
};

pub const Int32Value = struct {
    value: ?i32 = null,

    pub fn getValue(self: @This()) i32 {
        return self.value orelse 0;
    }
};

pub const UInt32Value = struct {
    value: ?u32 = null,

    pub fn getValue(self: @This()) u32 {
        return self.value orelse 0;
    }
};

pub const BoolValue = struct {
    value: ?bool = null,

    pub fn getValue(self: @This()) bool {
        return self.value orelse false;
    }
};

pub const StringValue = struct {
    value: ?[]const u8 = null,

    pub fn getValue(self: @This()) []const u8 {
        return self.value orelse "";
    }
};

pub const BytesValue = struct {
    value: ?[]const u8 = null,

    pub fn getValue(self: @This()) []const u8 {
        return self.value orelse "";
    }
};
