name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Install buf
        uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          setup_only: true

      - name: Setup
        run: just setup

      - name: Setup conformance
        if: runner.os != 'Windows'
        run: just setup-conformance

      - name: Build
        run: just build

      - name: Generate
        if: runner.os != 'Windows'
        run: |
          just generate
          just generate-wkt
          just generate-example
          just generate-conformance
          git status
          test -z "$(git status --porcelain)" # Check for uncommitted changes after generation

      - name: Test
        run: just test

      - name: Conformance
        if: runner.os != 'Windows'
        run: just conformance

      - name: Run example
        run: just run-example
